[tool.pyflow]
name = "kysy"
py_version = "3.9"
version = "2021.10.20"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
